framework:
    ide: 'phpstorm://open?url=file://%%f&line=%%l&/var/www/jakub/comPassMan/>C:\Users\Jakub.Reiter\Documents\PhpStormProjects\comPassMan\&/var/www/kamil/comPassMan/>C:\Users\Kamil.Hipsz\PhpstormProjects\comPassMan\'
